version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${APP_PORT}
      - DATABASE_URL=postgres://ddf_user:ddf_pass@postgres:5432/ddf
      - DDF_CLIENT_ID=your_id
      - DDF_CLIENT_SECRET=your_secret
    depends_on:
      - postgres
    networks:
      - bradsen-app

  nginx:
    container_name: bradsen-app-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '6962:80'
    environment:
      - APP_PORT=${APP_PORT}
    restart: always
    depends_on:
      - app
    networks:
      - bradsen-app

  postgres:
    image: postgres:15
    container_name: ddf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ddf
      POSTGRES_USER: ddf_user
      POSTGRES_PASSWORD: ddf_pass
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./listings.sql:/docker-entrypoint-initdb.d/listings.sql
    networks:
      - bradsen-app

volumes:
  pg_data:

networks:
  bradsen-app:
    driver: bridge
